### ISSUE TITLE
Ability to use day intead of date

### ISSUE THREAD

**Issue by xorob0** [soywod/kronos.vim#10]
If I know something is due for next wednesday, I don't want to open the calendar to see which date it is or to do calculations in my head.
Great work !

**Comment by soywod** [comment]
If I understand well, it's to add the ability to type something like `:2d` or `:1w3h`?

**Comment by soywod** [comment]
I push something on `datetime-python` branch #16 [[commit](https://github.com/soywod/kronos.vim/pull/16/commits/0d108be8e4557c8bf7dac7eac672684c9ad9dff1)]
