### ISSUE TITLE
If `:w` is issued while a context is active, all tasks not in the context are deleted

### ISSUE THREAD

**Issue by computations** [soywod/kronos.vim#18]
If I issue a `:w` while a context is active, then every task that isn't tagged with that context is deleted silently. This happens on the latest commit to master branch, with neovim version 0.3.5.

**Comment by soywod** [comment]
Fixed in https://github.com/soywod/kronos.vim/commit/f9336da6bc51073c070ca297d173c2caa040b00c, thank you for your feedback :ok_hand:
