### ISSUE TITLE
Removing/adding tag while updating task removes due date/time.

### ISSUE THREAD

**Issue by zachfox** [soywod/kronos.vim#2]
When I remove a tag with -<tag>, the tag is properly removed, but I also lose the due date/time. 

As a minimal working example:
`:K a new task +todo :24:2359`

Then enter the u mode:
```
u
-todo 
```

Which properly removes the tag "todo", but also removes the due date/time.

**Comment by soywod** [comment]
Thank you for your feedback, bug fixed :tada:

**Comment by zachfox** [comment]
Sure! Thanks for making an awesome tool. 👍
