### ISSUE TITLE
where are kronos task stored

### ISSUE THREAD

**Issue by kraxli** [soywod/kronos.vim#20]
Hi 
many thanks for this nice plugin! 
I am wondering where the **Kronos-tasks** (file) is/are **stored** to back it up.
Thanks! David

**Comment by soywod** [comment]
Hi!
By default it's in the plugin folder. For me, on Arch Linux + nvim, it's in `~/.config/nvim/plugged/kronos.vim/.database`. You can change it with `g:kronos_database`.
