### ISSUE TITLE
sorting by tags and/or due dates

### ISSUE THREAD

**Issue by kraxli** [soywod/kronos.vim#21]
is there a way to sort by tags and/or due dates?

**Comment by soywod** [comment]
Not yet. The only thing you can do is to filter by tags using the [context](https://github.com/soywod/kronos.vim#context). I will think how to do this and let you know. Feel free to propose a PR if you want :)

**Comment by soywod** [comment]
Functionality added https://github.com/soywod/kronos.vim/pull/26
