### ISSUE TITLE
custom shortcut keys are disabled in Kronos 

### ISSUE THREAD

**Issue by kraxli** [soywod/kronos.vim#23]
How can I enable my custom shortcut keys in Kronos? Most of them are disabled. 

Thanks
David

**Comment by soywod** [comment]
Check the [mapping section](https://github.com/soywod/kronos.vim#mappings). For eg, to set up a custom binding for the worktime, you can do `nmap <leader>w     <plug>(kronos-worktime)`.

**Comment by kraxli** [comment]
thanks! this works perfectly fine :-) .  
however, other mapping which I have set do not work, as e.g: `nmap <leader>nt :tabnew<cr>`

**Comment by soywod** [comment]
You mean that in a kronos buffer, you don't have access to other bindings right?

**Comment by kraxli** [comment]
yes, correct

**Comment by soywod** [comment]
I can't reproduce. My personal bindings still work in kronos buffer. Could you provide me your `vimrc` (the part with the kronos bindings and your personal bindings), your OS and your vim version?

**Comment by soywod** [comment]
Close due to inactivity.
