### ISSUE TITLE
Store tasks into a GitHub Gist

### ISSUE THREAD

**Issue by soywod** [soywod/kronos.vim#3]
What do you think of this idea ? So, many other clients could be developed (kronos.web, kronos.sys, kronos.app etc) and using this same Gist (kind of sync) ?

**Comment by soywod** [comment]
Poke started on branch [gist-sync](https://github.com/soywod/kronos.vim/tree/gist-sync)

**Comment by VincentCordobes** [comment]
bad idea

**Comment by soywod** [comment]
Feature merged :tada:
