### ISSUE TITLE
Show worktime for a single day or a specific date range

### ISSUE THREAD

**Issue by kristijanhusak** [soywod/kronos.vim#8]
Hi,

Is there a way to get worktime for a tag for a specific date range, day, or something like that?

I'm treating project as a tag, and i would like to see how much time i worked on it for a specific time range.

**Comment by soywod** [comment]
Hi @kristijanhusak,
For now, it's not possible, but I'll consider the case. I let you know. Or feel free to propose a PR :)

**Comment by kristijanhusak** [comment]
Ok, thanks.

I'm using latest version.

**Comment by soywod** [comment]
I checked a bit, it will need some refactor. Because for now, the worktime doesn't keep informations about the datetime. It's just a basic counter.

**Comment by kristijanhusak** [comment]
That looks nice!

**Comment by soywod** [comment]
I merged the feature. The UI is quite primitive for now, I'll do sth better later. But at least the feature is there (and well tested), I'm interested in your feedback!

**Comment by soywod** [comment]
I improved the UI (set table like other features), should be better now!

![image](https://user-images.githubusercontent.com/10437171/50566298-38930680-0d38-11e9-9338-1b5aa23279c1.png)

**Comment by kristijanhusak** [comment]
I did a quick test, looks nice. I can give you more feedback in a week or so, when i get back to work and start tracking properly. 
Only issue that crosses my mind at this point is that list of dates can get long at some point, so maybe filtering out only specific dates or a range of dates would be really awesome.

**Comment by soywod** [comment]
I could add params to the Worktime function. For now we only have tags, but I can add start date and end date on the same model as task due creation (`:ddmmYY:HHMM`), something like `<ddmmYY:HHMM` / `>ddmmYY:HHMM`

**Comment by kristijanhusak** [comment]
Yeah that should work.

**Comment by soywod** [comment]
I reopen this issue, since I'm working back on this:

> so maybe filtering out only specific dates or a range of dates would be really awesome.

**Comment by soywod** [comment]
@kristijanhusak I pushed sth, now you can filter your worktime by `>DDMMYY:HHMM` and `<DDMMYY:HHMM` (see [README](https://github.com/soywod/kronos.vim#worktime)). I will update the gif later. Thanks for you feedback!
